version: "3.9"

services:
  pg_db:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5456:5432"
    environment:
      - POSTGRES_DB=weather_new_db
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker

    volumes:
      - db:/var/lib/postgresql/data
    network_mode: "host"

volumes:
  db: